/*
  Warnings:

  - The primary key for the `Account` table will be changed.
  - Altering columns may cast BigInt to Integer. Verify data before running.
*/

-- Drop foreign keys
ALTER TABLE "public"."AccountScore" DROP CONSTRAINT IF EXISTS "AccountScore_accountId_fkey";
ALTER TABLE "public"."Campaign" DROP CONSTRAINT IF EXISTS "Campaign_accountId_fkey";

-- Alter Account table
ALTER TABLE "public"."Account" DROP CONSTRAINT IF EXISTS "Account_pkey";

-- Add accountId column
ALTER TABLE "public"."Account" ADD COLUMN "accountId" TEXT NOT NULL;

-- Alter id column to use identity (Postgres 10+ standard)
ALTER TABLE "public"."Account"
  ALTER COLUMN "id" SET DATA TYPE INTEGER,
  ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Add primary key back
ALTER TABLE "public"."Account" ADD CONSTRAINT "Account_pkey" PRIMARY KEY ("id");

-- Alter dependent tables
ALTER TABLE "public"."AccountScore" ALTER COLUMN "accountId" SET DATA TYPE INTEGER;
ALTER TABLE "public"."Campaign" ALTER COLUMN "accountId" SET DATA TYPE INTEGER;

-- Create unique index on accountId
CREATE UNIQUE INDEX IF NOT EXISTS "Account_accountId_key" ON "public"."Account"("accountId");

-- Add foreign keys back
ALTER TABLE "public"."Campaign"
  ADD CONSTRAINT "Campaign_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "public"."Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "public"."AccountScore"
  ADD CONSTRAINT "AccountScore_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "public"."Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
